---

- name: install xfce-desktop
  become: true
  action: >
    {{ ansible_pkg_mgr }} name="@xfce-desktop" state=present

- name: install xfce-apps
  become: true
  action: >
    {{ ansible_pkg_mgr }} name="@xfce-apps" state=present

- name: install xfce-extra-plugins
  become: true
  action: >
    {{ ansible_pkg_mgr }} name="@xfce-extra-plugins" state=present

- name: install xfce-media
  become: true
  action: >
    {{ ansible_pkg_mgr }} name="@xfce-media" state=present

- name: install xfce-office
  become: true
  action: >
    {{ ansible_pkg_mgr }} name="@xfce-office" state=present

- name: install xfce-extras
  become: true
  action: >
    {{ ansible_pkg_mgr }} name= {{ item }} state=present
  with_items: 
    - xfce4-cpufreq-plugin
    - xfce4-systemload-plugin

- name: install light-locker
  become: true
  dnf: name=light-locker state=present
  when: ansible_distribution == "Fedora"

- name: remove xscreensaver
  become: true
  dnf:
    name: 'xscreensaver*'
    state: absent
  when: ansible_distribution == "Fedora"
