---
# defaults file for pyenv
pyenv_env: "user"
pyenv_path: "{% if pyenv_env == 'user' %}{{ ansible_env.HOME }}/.pyenv{% else %}/usr/local/pyenv{% endif %}"
pyenv_owner: "{{ ansible_env.USER }}"
pyenv_setting_path: "{% if pyenv_env == 'user' %}~/.bashrc{% else %}/etc/profile.d/pyenv.sh{% endif %}"
pyenv_update_git_install: no
pyenv_enable_autocompletion: no
pyenv_python_versions:
  - 3.6.5
pyenv_virtualenvs:
  - { venv_name: "latest", py_version: "3.6.5" }

pyenv_update: no

pyenv_redhat_packages:
  - git
  - gcc
  - libselinux-python
  - zlib-devel
  - openssl-devel
  - bzip2-devel
  - readline-devel
  - libffi-devel
  - sqlite-devel
  - gdbm-devel
