---

- name: install 'Audio Production' package group
  become: true
  dnf:
    name: "@Audio Production"
    state: present

- name: install networkmanager-submodules
  become: true
  action: >
    {{ ansible_pkg_mgr }} name="@networkmanager-submodules" state=present update_cache=yes




