---
- name: install epel
  become: true
  yum: name=epel-release state=present

- name: install xfce
  become: true
  yum: name="@^xfce" state=present

- name: install gnucash
  become: true
  yum: name=gnucash state=present


