---
- include: SL7.yml
  when: ansible_distribution == "Scientific Linux"

- include: Fedora.yml
  when: ansible_distribution == "Fedora"

- name: install epel
  become: true
  yum: name=epel-release state=present
  when: ansible_distribution == "Scientific Linux"

- name: install xfce-desktop
  become: true
  yum: name="@xfce-desktop" state=present

- name: install xfce-apps
  become: true
  yum: name="@xfce-apps" state=present

- name: install xfce-extra-plugins
  become: true
  yum: name="@xfce-extra-plugins" state=present

- name: install xfce-media
  become: true
  yum: name="@xfce-media" state=present

- name: install xfce-office
  become: true
  yum: name="@xfce-office" state=present

- name: install xfce-extras
  become: true
  yum:
    name: 
      - xfce4-cpufreq-plugin
      - xfce4-systemload-plugin

- name: install audacity
  become: true
  yum: name=audacity state=present

- name: install gnucash
  become: true
  yum: name=gnucash state=present

- name: install arrow development packages
  become: true
  yum: 
    name: "{{arrow_redhat_packages}}" 
    state: present
