---
- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: install epel
  become: true
  yum: name=epel-release state=present

- name: install xfce
  become: true
  yum: name="@^xfce" state=present

- name: install xfce-extras
  become: true
  yum:
    name: 
      - xfce4-cpufreq-plugin
      - xfce4-systemload-plugin

- name: install audacity
  become: true
  yum: name=audacity state=present

- name: install gnucash
  become: true
  yum: name=gnucash state=present

- name: install arrow development packages
  become: true
  yum: 
    name: "{{arrow_redhat_packages}}" 
    state: present
