#
# Makefile
# Ryan Mackenzie White, 2018-12-30 09:50
#

all:
	@echo "Makefile needs your attention"

.PHONY: ${TARGETS}

install:
	ansible-playbook -i '127.0.0.1,' workstation.yml --ask-become-pass

# vim:ft=make
#
